### ISSUE TITLE
pipeline container not start

### ISSUE THREAD

**Issue by didlawowo** [deployKF/deployKF#73] opened 2023-12-22 18:17 UTC
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.3

### Kubernetes Version

```shell
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1203001

node
│ System Info:                                                                                                                                                                             │
│   Machine ID:                 d162e776c80f9c6d0af8fb5758a3572e                                                                                                                           │
│   System UUID:                d162e776-c80f-9c6d-0af8-fb5758a3572e                                                                                                                       │
│   Boot ID:                    64e951a0-e47e-4046-9f6e-e2bd15f7d766                                                                                                                       │
│   Kernel Version:             6.1.58+                                                                                                                                                    │
│   OS Image:                   Container-Optimized OS from Google                                                                                                                         │
│   Operating System:           linux                                                                                                                                                      │
│   Architecture:               amd64                                                                                                                                                      │
│   Container Runtime Version:  containerd://1.7.7                                                                                                                                         │
│   Kubelet Version:            v1.28.3-gke.1203001                                                                                                                                        │
│   Kube-Proxy Version:         v1.28.3-gke.1203001
```

### Description

some container not start and crash loop backoff after install

Error: failed to create containerd task: failed to create shim task: OCI runtime create faile │
│ d: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown 

for pods
ml-pipeline-viewer-crd-54d99546c9-5zbqf
ml-pipeline-scheduledworkflow-d888f97fd-q99qd      
 ml-pipeline-557fcdd8f5-ldj4k

### Relevant Logs

```shell
no logs
```

### deployKF Values (Optional)

```yaml
nothing on this side configuration

pushing istio config  at ingress mode
```

**Comment by didlawowo** [comment] 2023-12-28 11:12
i really appreciate any help about this ? cause i really would like to use deploykf.

i think it's a problem about gke ? i would try on eks

**Comment by thesuperzapper** [comment] 2024-01-23 19:07
@didlawowo are you still experiencing this issue?

Because it looks more like your cluster was not working properly, rather than an issue with deployKF.

**Comment by didlawowo** [comment] 2024-04-30 18:27
i' don't have time anymore maybe i  have to test with latest version one another cluster

**Comment by thesuperzapper** [comment] 2024-04-30 18:55
@didlawowo ok, I am going to close this for now.

Please re-open if you encounter the same issue, so we can try and reproduce it.

**Closed by thesuperzapper** 2024-04-30 18:55 UTC
Labels: kind/bug, status/needs-discussion
