### ISSUE TITLE
Race condition in cert-manager app with certificate creation 

### ISSUE THREAD

**Issue by theNewFlesh** [deployKF/deployKF#23] opened 2023-09-06 00:28 UTC
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-21T14:01:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Description

I was running through app of apps deployment process and it fails at the cert manager step. Resyncing/deleting doesn't work.

Default storage class: longhorn

### Relevant Logs

```shell
MountVolume.SetUp failed for volume "tls" : secret "trust-manager-tls" not found
```

**Comment by thesuperzapper** [comment] 2023-09-06 03:25
Can you share the Pod logs for the `trust-manager` deployment, and possibly the `cert-manager` deployment also?

**Comment by thesuperzapper** [comment] 2023-09-09 02:48
@theNewFlesh this is just an eventual consistency thing, takes a while for cert-manager to make the secret, especially because we are installing cert-manager and trust-manager at the same time.

As part of the next release, I am going to enable "sync retry" by default on the cert-manager app (to avoid the "first sync always fails" issue), but even with retries, it will still take a few minuets to sync.

**Comment by thesuperzapper** [comment] 2023-09-12 00:19
Sorry, I closed this prematurely as I misunderstood the issue.

The problem is actually a race condition between `cert-manager` and `trust-manager`, because `trust-manager` wants to create a Certificate and mount its Secret, but it cant do this until `cert-manager` is ready.

I have a fix which will be in the next version of deployKF.

**Comment by theNewFlesh** [comment] 2023-09-12 01:12
Awesome

**Closed** 2023-09-21 19:01 UTC
Labels: kind/bug, priority/medium
